# NumPy
**Learning Objectives**
>- Understand what NumPy is and why it's useful.
>- Create and explore NumPy arrays.
>- Perform basic operations on arrays.
>- Begin thinking in terms of vectorized data instead of loops.

**What is NumPy?**
>- NumPy (short for Numerical Python) is a powerful open-source Python library used for numerical computing. It provides support for:
>    - Multidimensional arrays (called ndarray)
>    - Mathematical operations on arrays
>    - Linear algebra, Statistics, Fourier transforms, and much more!
>    - Efficient handling of large datasets

**Key Features**
>- Fast array operations: Much faster than native Python lists
>- Vectorization: Avoids slow Python loops by applying operations to entire arrays
>- Integration: Works well with other libraries like SciPy, Pandas, Matplotlib, Seaborn, Plotly

#### Creating NumPy Arrays
>- `np.arange(start, stop, step)`
>- `np.linspace(start, stop, num_of_pts)`
>- `np.array()`
>- `np.ones(shape)`
>- `np.zeros(shape)`

In [1]:
import numpy as np

# np.arange() is similar to the builtin range() but better
numbers = np.arange(1, 5)
print(type(numbers), numbers)
numbers = np.arange(1, 15, 2)
print(numbers)
print(*numbers)

# range() only works with integers
# .arange() can work with integers or floats
numbers = np.arange(1, 5, .3)
print(numbers)
numbers = np.arange(2.3, 5.1, .25)
print(numbers)

<class 'numpy.ndarray'> [1 2 3 4]
[ 1  3  5  7  9 11 13]
1 3 5 7 9 11 13
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9]
[2.3  2.55 2.8  3.05 3.3  3.55 3.8  4.05 4.3  4.55 4.8  5.05]


In [2]:
import numpy as np

# np.linspace() creates evenly spaced points
# np.linspace(start, stop, number_of_points)
nums = np.linspace(0, 10, 6)
print(nums)
nums = np.linspace(0, 1, 12)
print(nums)

[ 0.  2.  4.  6.  8. 10.]
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


**Practice Problems**
1. Use `np.arange()` to create numbers from 1 to 13 with 20 evenly spaced points - this is meant to be a question that takes some time so that it motivates the reason .linspace() exists.
1. Use `np.linspace()` to create numbers from 1 to 13 with 20 evenly spaced points.
1. Use `np.arange()` to create numbers 0 .1 .2 .3 .4 ... .9.
1. Be creative! Create examples where you use `np.arange()` and `np.linspace()`.

In [ ]:
import numpy as np

# np.array() Creates a numpy array from a list, tuple, or set
# np.ones(shape) creates a n-dim numpy array
# np.zeros(shape) creates a n-dim numpy array
nums = np.array([1, 2, 3])
print(nums)
ones = np.ones(3)
print("ones:", ones)
ones = np.ones([3, 2])
print("ones:\n", ones)

#### NumPy Math and Statistics
>- +, -, *, /, //, %
>- `np.min(a)`
>- `np.max(a)`
>- `np.mean(a)`
>- `np.median(a)`
>- `np.sum(a)`
>- `np.prod(a)`
>- `np.var(a)`
>- `np.std(a)`

In [ ]:
import numpy as np

nums = np.array([1, 2, 3, 1])
print(f"nums: {nums}")
print(f"+1.61: {nums + 2.718}")
print(f"max: {np.max(nums)}")
print(f"avg: {np.mean(nums)}")
print(f"median: {np.median(nums)}")
print(f"prod: {np.prod(nums)}")


**Practice Problems**
1. Output the min value of the numpy array.
1. Create a numpy array where the max is 10 and mean is 5.
1. Create a numpy array where the max is 8 and mean is 5.
1. Create a function that calculates the factorial of a number only using numpy. 
1. Explore the `np.std()` method (standard deviation), is this the standard deviation or population standard deviation?

#### NumPy Element-wise Operations
>- `np.add(a, b)`
>- `np.subtract(a, b)`
>- `np.multiple(a, b)`
>- `np.divide(a, b)`
>- `np.power(a, b)`
>- `np.sqrt(a)`
>- `np.exp(a)`
>- `np.log(a)`

In [ ]:
import numpy as np

exam1 = np.array([78, 89])
exam2 = np.array([95, 67])

print(f"exam1, exam2: {exam1}, {exam2}")
print(f"add exam1 + 10  : {np.add(exam1, 10)}")
print(f"add exam1+exam2 : {np.add(exam1, exam2)}")
print(f"subtracting: {np.subtract(exam1, exam2)}")
np.set_printoptions(precision=2)
print(f"power: {np.power([1, 2, 8], 1/3)}")

**Practice Problems**
1. Find the average of exam1.
1. Find the average of all exam scores.
1. Assume that the maximum points for exam1 is 95. And assume that the exam1 scores are the raw scores from the exam. Find the percentage score for each element of exam1.
1. Explore the `np.exp(`) and `np.log()` methods. The `np.exp()` is some number raised to the elements of the given numpy array. What is this some number? (hint: start by creating a numpy array with numbers that are "easy" to calcuate with).
1. Define two numpy arrays, then raise the second numpy array to the power of the first numpy array.
1. Be creative! Create examples that make you explore and understand the numpy methods.  

#### Adding Element(s), Deleting Element(s), Sorting

In [ ]:
import numpy as np

nums = np.arange(1, 3)
print(f"nums: {nums}")
np.append(nums, 10)
print(f"nums: {nums}")
nums = np.append(nums, 10)
print(f"nums: {nums}")
nums = np.append(nums, np.array([7, 8, 9]))
print(f"nums: {nums}")
print(f"sort: {np.sort(nums)}") # todo: slice to reverse order

**Practice Problems**
1. The `np.delete()` method works similarly to the `np.append()` method. Create one numpy array and use the `np.delete()` method to remove one element.
1. The `np.delete()` method works simiarly to the `np.append()` method. Create two numpy arrays and use the `np.delete()` method to remove items from the second numpy array. 
1. Create a non-sorted numpy array of any length. Use the `np.sort()` method to sort the array, be sure to update your original created variable. Then print the items in reverse order (hint: use slicing)